{% set name = "grayskull" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03ac2942afdaa85d5b8aad9aaf07c52cbec0c3a98c821da389272a28ce0fe8d2

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
    - conda-grayskull = grayskull.__main__:main
    - conda-greyskull = grayskull.__main__:main

outputs:
  - name: grayskull
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - setuptools >=30.3.0
        - setuptools_scm
      run:
        - python >=3.8
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - stdlib-list
        - pip
        - setuptools >=30.3.0
        - rapidfuzz >=1.7.1
        - progressbar2 >=3.53.0
        - colorama
        - conda-souschef >=2.2.3
        - pkginfo
        - packaging >=21.3
        - tomli
        - tomli-w
        - beautifulsoup4
    test:
      imports:
        - grayskull
      commands:
        - pip check
        - grayskull --help
        - greyskull --help
      requires:
        - pip

  - name: greyskull
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('grayskull', max_pin="x.x.x") }}
    test:
      imports:
        - grayskull
      commands:
        - grayskull --help
        - greyskull --help

about:
  home: https://pypi.org/project/grayskull/
  summary: Project to generate recipes for conda.
  dev_url: https://github.com/conda-incubator/grayskull
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
