{% set name = "grayskull" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 814cb41ac28e0d735362fd2fae8ba261d567464164466ca48bdca8b3063532ec

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main

outputs:
  - name: grayskull
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - setuptools >=30.3.0
        - setuptools_scm
      run:
        - colorama
        - rapidfuzz >=1.7.1
        - pip
        - progressbar2 >=3.53.0
        - python >=3.8
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - setuptools >=30.3.0
        - stdlib-list
        - git
        - conda-souschef >=2.1.1
        - pkginfo
    test:
      imports:
        - grayskull
      commands:
        - pip check
        - grayskull --help
        - greyskull --help
      requires:
        - pip

  - name: greyskull
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('grayskull', max_pin="x.x.x") }}
    test:
      imports:
        - grayskull
      commands:
        - grayskull --help
        - greyskull --help

about:
  home: https://pypi.org/project/grayskull/
  summary: Project to generate recipes for conda.
  dev_url: https://github.com/conda-incubator/grayskull
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
