{% set name = "grayskull" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39ec33a74b716c4e3ed876733669866f1b0743a242e16255e772e793598cb2dd

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
    - conda-grayskull = grayskull.__main__:main
    - conda-greyskull = grayskull.__main__:main

outputs:
  - name: grayskull
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - setuptools >=61
        - setuptools-scm >=6.2
        - pip
      run:
        - python >=3.8
        - beautifulsoup4
        - colorama
        - conda-souschef >=2.2.3
        - packaging >=21.3
        - pip
        - pkginfo
        - progressbar2 >=3.53.0
        - rapidfuzz >=3.0.0
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - setuptools >=30.3.0
        - semver >=3.0.0,<3.1.dev0
        - stdlib-list
        - tomli
        - tomli-w
    test:
      imports:
        - grayskull
      commands:
        - pip check
        - grayskull --help
        - greyskull --help
        - conda-grayskull --help
        - conda-greyskull --help
      requires:
        - pip

  - name: greyskull
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('grayskull', max_pin="x.x.x") }}
    test:
      imports:
        - grayskull
      commands:
        - grayskull --help
        - greyskull --help

about:
  home: https://pypi.org/project/grayskull/
  summary: Project to generate recipes for conda.
  dev_url: https://github.com/conda-incubator/grayskull
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - maresb
    - marcelotrevisani
