# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.0.2"
  # per upstream metadata should be 3.10, but conda-recipe-manager requires 3.11
  python_min: "3.11"

recipe:
  name: grayskull-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/grayskull/grayskull-${{ version }}.tar.gz
  sha256: 8d0f5c6ab1266d42ce8b8ada06d56c290791b2c19d2285067e314af86687a6ad

build:
  number: 0

outputs:
  - package:
      name: grayskull
    build:
      noarch: python
      python:
        entry_points:
          - conda-grayskull = grayskull.__main__:main
          - conda-greyskull = grayskull.__main__:main
          - grayskull = grayskull.__main__:main
          - greyskull = grayskull.__main__:main
      script:
        - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools >=61
        - setuptools-scm >=6.2
      run:
        - beautifulsoup4
        - colorama
        - conda-souschef >=3.0.1
        - packaging >=21.3
        - pip
        - pkginfo
        - progressbar2 >=3.53.0
        - python >=${{ python_min }}
        - rapidfuzz >=3.0.0
        - requests
        - ruamel.yaml >=0.16.10
        - ruamel.yaml.jinja2
        - setuptools >=30.3.0
        - stdlib-list
        - tomli
        - tomli-w
        # undeclared dependency not on PyPI, needed for v1 recipes
        - conda-recipe-manager
    tests:
      - python:
          imports: grayskull
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - grayskull --help
          - greyskull --help
          - conda-grayskull --help
          - conda-greyskull --help

  - package:
      name: greyskull
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("grayskull", upper_bound="x.x.x") }}
    tests:
      - script:
          - grayskull --help
          - greyskull --help
          - conda-grayskull --help
          - conda-greyskull --help

about:
  summary: Project to generate recipes for conda packages
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/grayskull
  repository: https://github.com/conda/grayskull

extra:
  feedstock-name: grayskull
  recipe-maintainers:
    - BastianZim
    - maresb
    - marcelotrevisani
